name: Release

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write
jobs:
  release_docker:
    runs-on: ubuntu-latest
    
  steps:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: Mmx233/GoReleaseCli@v1.2.2
        with:
          target: ./cmd/derper
          compress: tar.gz

      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.tar.gz
          prerelease: false
